---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        ports:
        - name: sql-port
          containerPort: 5432
          protocol: TCP
        name: posgres
        env:
        - name: POSTGRES_DB 
          value: testdatabase
        - name: POSTGRES_USER 
          value: testuser
        - name: POSTGRES_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: database
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
