---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-game-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-game
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: my-game
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: game
        ports:
        - name: vnc-server
          containerPort: 5900
          protocol: TCP
